### ISSUE TITLE
Vagrant attempted to execute the capability 'change_host_name'

### ISSUE THREAD

**Issue by gregsilin** [mkrcah/virtual-zookeeper-cluster#4] opened 2016-08-16 16:54 UTC
error message:

```
Vagrant attempted to execute the capability 'change_host_name'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability
```

vagrant `1.8.5`
virtual box `Version 5.1.2 r108956`

underlying VM OS

```
==> default: Adding box 'ubuntu/trusty64' (v20160809.1.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160809.1.0/providers/virtualbox.box
```

This is happening against current master (`cc928257c16e27a39f1e21a4f93e21885926c852`)

**Comment by mkrcah** [comment] 2016-08-16 17:15
Thanks, I can reproduce this. I'm looking into it

**Comment by gregsilin** [comment] 2016-08-16 17:34
@mkrcah thanks very much.  My colleague @bmusial located the revert that fixed the breaking change in vagrant, not sure if that will help: https://github.com/mitchellh/vagrant/pull/7632/commits/00fa49191dba2bb7c6322fa8df9327ca505c0b41

**Comment by mkrcah** [comment] 2016-08-16 17:40
Fixed in the latest commit along with other cleanup fixes. 

The problem was that Vagrant couldn't detect Ubuntu OS on 12.04. Bumping Ubuntu to 14.04 solved the problem. 

Can you check on the latest commit? Don't forget to run `vagrant destroy` before `vagrant up`.

**Comment by gregsilin** [comment] 2016-08-16 19:02
Confirmed, it works.  Thanks for the super fast turnaround!!

**Comment by bkmu** [comment] 2016-08-16 19:03
I rebuilt locally as well and see it working -- Thanks @mkrcah!  I believe this issue can be moved to closed.

**Comment by mkrcah** [comment] 2016-08-16 19:58
Great, have a nice day, guys!

**Closed as completed by mkrcah** 2016-08-16 19:58 UTC
